version: 2
updates:
  # Github Actions dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      
  # Maven dependencies
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly