name: Run tests

on:
  workflow_dispatch:
    inputs:
      jdk-version:
        description: 'JDK version to use'
        required: true
        default: '17'
        type: choice
        options:
          - 17
          - 21
          - 25
      implementation:
        description: 'Implementation to test (yasson or johnzon)'
        required: true
        default: 'yasson'
        type: choice
        options:
          - yasson
          - johnzon

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up JDK ${{ github.event.inputs.jdk-version }}
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:
        java-version: ${{ github.event.inputs.jdk-version }}
        distribution: 'temurin'
        cache: maven
    - name: Test ${{ github.event.inputs.implementation }}
      run: mvn clean test -f ${{ github.event.inputs.implementation }}.xml